language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OzR6bbXKaKz4eCxQ8ymadpfr3ymZ1HFI1EHImbvSUqgYirVBf6oEnVVkW8mm7GVmX6LhFF+Wnbbrom9s7oJUO6RuILXawl+bvDgyrGlvJ2MhJpEzYoIX8eB5ciY6J73nGfEKiglVbvEEph8IYWafLqUCnM+CrV6bB7zuL8MfLQt22XDxW8VdjSZBSwVBAP3Okt15fE5iaql5GcdstP9XScXnTjsM2FtEIMu18KgHBKz5xYMKfd0cUBoOqomEX4QvOPcbQw4XgIMu0E6eO67lyv5CtkwYPs8dRafJjY39URXdOgV/ERZ2xC/2Y0rBFOe2V8sFKnBwFgEuAf+vR3rxfqrF/SCrKoBbiELYBrDqUqPIS+62pDoVXEl3XP5flJqk/w4plgUZ9/7WepFePhxOG8gmCKHVXm2cohIEgLTgXBoDuq/u3x+HYIs4dcl0aKorYTa/XZJh/7JKbEG5TChOJY5z6zykoqz7RIO0iz0UFIB940YIoVoLV3aeCxAErl5gOS+x4om8QdbHL1s+Dsq+6j0IKqWHG9TG7nY8lD6gFla/Ap/HCj1rtCKcrRQhyWCU2bk67pB+96/rxd/lD8S2FqxWRXO9fZcoqbil5F0XJvwB+YgQ0wh8wrUUpKnZmroV5YAoPgnxyOC0Kv2r+a6OUGXw1d/GSw1LyaR9LdQKx+c=
  file:
    - 'html-element-attributes.js'
    - 'html-element-attributes.min.js'
  on:
    tags: true
